import com.android.build.api.variant.HasHostTestsBuilder
import com.android.build.api.variant.HostTestBuilder

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.kotlin.multiplatform)
    // Consumes the profile generated by :baselineprofile-tv and bakes it into
    // the release APK so profileinstaller can AOT-compile hot paths on first
    // run — first launches otherwise JIT the Home feed while the user browses.
    alias(libs.plugins.androidx.baselineprofile)
}

// See androidApp's build.gradle.kts for the channel rationale.
val siloReleaseChannels = listOf("internal", "alpha", "beta", "production", "sideload", "dev")

val siloVersionName = providers
    .gradleProperty("siloVersionName")
    .orElse(providers.environmentVariable("SILO_VERSION_NAME"))
    // Release builds override this from the validated Git tag in
    // android-build.yml. Keep local/dev builds aligned with the latest release.
    .orElse("0.3.11")

val siloDisplayVersion = providers
    .gradleProperty("siloDisplayVersion")
    .orElse(providers.environmentVariable("SILO_DISPLAY_VERSION"))
    .orElse(siloVersionName)

// The per-marketing-version build counter (TestFlight-style). It is folded into
// the versionCode by CI, but the app also reports it verbatim to the server
// (X-Silo-Client-Build), so it has to survive as its own value rather than
// being reverse-engineered from the versionCode.
val siloBuildNumber = providers
    .gradleProperty("siloBuildNumber")
    .orElse(providers.environmentVariable("SILO_BUILD_NUMBER"))
    .map { value ->
        val build = value.toIntOrNull() ?: error("siloBuildNumber must be an integer.")
        // The same 0..999 window release.yml and the Fastfile enforce, so a
        // hand-run build can't stamp a counter the release scheme could never
        // produce. 0 is the unstamped local default; CI itself requires 1..999.
        require(build in 0..999) {
            "siloBuildNumber must be between 0 and 999 (0 marks an unstamped local build)."
        }
        build.toString()
    }
    // Local/dev builds have no CI build number; 0 marks "not a release build".
    .orElse("0")

// The Play track this artifact is uploaded to, or how it reaches a device
// without Play. See androidApp's build.gradle.kts.
val siloReleaseChannel = providers
    .gradleProperty("siloReleaseChannel")
    .orElse(providers.environmentVariable("SILO_RELEASE_CHANNEL"))
    .map { value ->
        val channel = value.trim().lowercase()
        require(channel in siloReleaseChannels) {
            "siloReleaseChannel must be one of ${siloReleaseChannels.joinToString("/")} (got '$value')."
        }
        channel
    }
    .orElse("sideload")

val siloVersionCode = providers
    .gradleProperty("siloVersionCode")
    .orElse(providers.environmentVariable("SILO_VERSION_CODE"))
    .map { value ->
        val code = value.toIntOrNull() ?: error("siloVersionCode must be an integer.")
        require(code > 0) { "siloVersionCode must be positive." }
        // The *2 (+1 for TV) form-factor multiplier applied at versionCode
        // assignment must stay under Google Play's 2_100_000_000 ceiling.
        require(code <= 1_049_999_999) {
            "siloVersionCode must be <= 1_049_999_999 so the form-factor multiplier " +
                "keeps both artifacts under Google Play's 2_100_000_000 versionCode limit."
        }
        code
    }
    // Bump this per release. base -> phone = base*2, TV = base*2+1. base 6 was
    // the 12/13 build; base 7 -> phone 14, TV 15.
    .orElse(7)

// See androidApp/build.gradle.kts: APK ABI splits break the App Bundle build,
// so disable them whenever a bundle task is invoked.
val isBuildingBundle = gradle.startParameter.taskNames.any {
    it.contains("bundle", ignoreCase = true)
}

kotlin {
    androidTarget {
        compilations.all {
            kotlinOptions {
                jvmTarget = "21"
            }
        }
    }

    sourceSets {
        androidMain.dependencies {
            implementation(project(":shared"))
            implementation(project(":android-shared"))
            implementation(compose.material3)
            implementation(compose.materialIconsExtended)
            implementation(compose.ui)
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(libs.activity.compose)
            implementation(libs.lifecycle.runtime.compose)
            implementation(libs.lifecycle.viewmodel.compose)
            // ProcessLifecycleOwner for the notifications foreground starter.
            implementation(libs.lifecycle.process)
            implementation(libs.navigation.compose)
            implementation(libs.koin.android)
            implementation(libs.koin.compose)
            implementation(libs.koin.compose.viewmodel)
            implementation(libs.coil.compose)
            implementation(libs.coil.network.okhttp)
            implementation(libs.media3.exoplayer)
            implementation(libs.media3.exoplayer.hls)
            implementation(libs.media3.datasource.okhttp)
            implementation(libs.media3.ui)
            implementation(libs.media3.session)
            implementation(libs.media3.common.ktx)
            implementation(libs.kotlinx.coroutines.android)
            implementation(libs.kotlinx.serialization.json)

            // Preferences persistence (playback quality, subtitle defaults, etc.).
            implementation(libs.datastore.preferences)

            // Compose for TV — focus-aware TV-optimized components.
            implementation(libs.tv.material)

            // Palette — bitmap accent-color extraction for the ambient hero backdrop (A.2).
            implementation(libs.androidx.palette)

            // Watch Next launcher tiles (sub-project B).
            implementation(libs.androidx.tvprovider)
            implementation(libs.androidx.work.runtime.ktx)
            implementation(libs.koin.androidx.workmanager)

            // QR-code rendering for device-login (sub-project C).
            implementation(libs.zxing.core)
            // Installs the Baseline Profile into the app at first run so hot paths
            // are AOT-compiled — faster cold start on TV hardware.
            implementation(libs.androidx.profileinstaller)
        }

        // JUnit 4 behavior tests plus a small Robolectric Compose harness for
        // focus and accessibility semantics that cannot be verified from
        // source text.
        androidUnitTest.dependencies {
            implementation(kotlin("test"))
            implementation(kotlin("test-junit"))
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.robolectric)
            implementation(libs.androidx.test.core)
            implementation(libs.compose.ui.test.junit4)
            // NotificationRow's constructor default uses JsonObject; the inbox
            // formatter test constructs rows directly, so json must be on the
            // test classpath.
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.ktor.client.mock)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.json)
        }
    }
}

android {
    val allowDebugReleaseSigning = providers
        .gradleProperty("allowDebugReleaseSigning")
        .orElse(providers.environmentVariable("ALLOW_DEBUG_RELEASE_SIGNING"))
        .map(String::toBoolean)
        .getOrElse(false)

    namespace = "org.siloserver.silo.tv"
    compileSdk = 36
    defaultConfig {
        // Shares one Play listing with the phone app, so both must use the
        // same applicationId. Play routes phone vs TV builds by manifest
        // feature filtering (this app requires android.software.leanback; the
        // phone app requires android.hardware.touchscreen). The `namespace`
        // above stays distinct so the generated R/BuildConfig classes don't
        // collide with the phone module.
        applicationId = "org.siloserver.silo"
        minSdk = 24
        targetSdk = 36
        // Two artifacts under one listing need distinct versionCodes: phone =
        // base*2, TV = base*2+1, so each release bumps both by 2 with no reuse.
        versionCode = siloVersionCode.get() * 2 + 1
        versionName = siloVersionName.get()
        buildConfigField("String", "DISPLAY_VERSION", "\"${siloDisplayVersion.get()}\"")
        // Reported to the server as X-Silo-Client-Build and shown on the About
        // row, so both name the same build the way Play and TestFlight do:
        // "Silo Android TV 1.0.0 (5)".
        buildConfigField("String", "BUILD_NUMBER", "\"${siloBuildNumber.get()}\"")
        // Shadow the android-shared BuildConfig field so per-app flavors can
        // override without rebuilding the shared module. See androidApp's
        // build.gradle.kts for rationale.
        buildConfigField("boolean", "FFMPEG_AUDIO_ENABLED", "true")
    }
    buildFeatures {
        compose = true
        buildConfig = true
    }
    // Release signing comes from the environment (CI decodes the keystore from
    // a GitHub secret); shared with :androidApp so both apps carry the same
    // signing identity. See that file for rationale.
    val releaseKeystorePath = providers.environmentVariable("SILO_RELEASE_KEYSTORE").orNull
    val hasReleaseSigning = !releaseKeystorePath.isNullOrBlank()
    signingConfigs {
        if (hasReleaseSigning) {
            create("release") {
                storeFile = file(releaseKeystorePath!!)
                storePassword = providers.environmentVariable("SILO_RELEASE_KEYSTORE_PASSWORD").orNull
                keyAlias = providers.environmentVariable("SILO_RELEASE_KEY_ALIAS").orNull
                // The key password may differ from the keystore password; fall
                // back to the keystore password when they're the same.
                keyPassword = providers.environmentVariable("SILO_RELEASE_KEY_PASSWORD").orNull
                    ?.takeIf { it.isNotBlank() }
                    ?: providers.environmentVariable("SILO_RELEASE_KEYSTORE_PASSWORD").orNull
            }
        }
    }
    buildTypes {
        debug {
            buildConfigField("String", "RELEASE_CHANNEL", "\"dev\"")
        }
        release {
            buildConfigField("String", "RELEASE_CHANNEL", "\"${siloReleaseChannel.get()}\"")
            // Launch-prep: full R8 + resource shrinking, sharing the root
            // proguard-rules.pro with :androidApp (same reflection/JNI-heavy
            // shared + android-shared stack). R8 breakage is runtime-only, so a
            // minified install must be smoke-tested on a TV before shipping.
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                rootProject.file("proguard-rules.pro"),
            )
            if (hasReleaseSigning) {
                signingConfig = signingConfigs.getByName("release")
            } else if (allowDebugReleaseSigning) {
                // Debug-sign release builds for local smoke tests when
                // explicitly opted in and no release keystore is available.
                signingConfig = signingConfigs.getByName("debug")
            }
        }
    }
    // Mirror androidApp's ABI split strategy. See that file for rationale.
    bundle {
        abi {
            enableSplit = true
        }
    }
    splits {
        abi {
            // Off for bundle builds — the AAB handles per-ABI delivery itself.
            isEnable = !isBuildingBundle
            reset()
            include("arm64-v8a", "armeabi-v7a", "x86_64")
            isUniversalApk = true
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
        isCoreLibraryDesugaringEnabled = true
    }
    testOptions {
        unitTests {
            // Default to safe no-op stubs for pure JVM tests that touch android.*;
            // the focused Compose semantics suite opts into Robolectric explicitly.
            isReturnDefaultValues = true
            isIncludeAndroidResources = true
        }
    }
    packaging {
        resources {
            // BouncyCastle (bcprov/bctls/bcutil) + jspecify each ship this OSGi
            // multi-release stub; drop the duplicates so the APK packages.
            excludes += "/META-INF/versions/*/OSGI-INF/MANIFEST.MF"
        }
    }

    // Lint had never run on this project. The two crashes it would have caught
    // — a Spatializer call gated at API 31 when the class arrives at 32, and a
    // getAddress() call with no guard at all — both shipped from this module,
    // which app-level lint does not analyse unless asked. Hence the gate here
    // and checkDependencies in the apps.
    //
    // The baseline holds today's known findings (overwhelmingly desugared
    // java.* calls and deliberate media3 @UnstableApi usage) so that only NEW
    // violations fail. Delete it and regenerate deliberately; do not add to it
    // to make a build pass.
    lint {
        // Without this, none of android-shared is examined.
        checkDependencies = true
        baseline = file("lint-baseline.xml")
        abortOnError = true
        fatal += setOf("NewApi", "InlinedApi")
        checkReleaseBuilds = true
    }
}

// The Robolectric suites need the test ComponentActivity in the merged
// manifest, and that dependency is deliberately debug-only so it can never
// reach the release APK. The consequence is that those same tests cannot run
// against the release variant at all — they fail resolving the activity rather
// than telling you anything about release.
//
// Running them once, on debug, is the whole of their value: unit tests are not
// minified, so the release variant exercises no different code. This was found
// by a flaky test in another module aborting `gradlew test` before the release
// task was ever reached.
androidComponents {
    beforeVariants(selector().withBuildType("release")) { variant ->
        // Host-tests API rather than `variant.enableUnitTest`, which AGP 8.10.1
        // deprecates and AGP 9.0 removes.
        (variant as HasHostTestsBuilder)
            .hostTests[HostTestBuilder.UNIT_TEST_TYPE]
            ?.enable = false
    }
}

dependencies {
    coreLibraryDesugaring(libs.desugar.jdk.libs)
    debugImplementation(libs.compose.ui.test.manifest)
    // The generated Baseline Profile artifact (see :baselineprofile-tv).
    baselineProfile(project(":baselineprofile-tv"))
}
